version: '3.8'

services:
  colinker-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/npm-cache:/tmp/npm-cache
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: npm start